### ISSUE TITLE
Infinite loop suspected while learning in a 15x15 square

### ISSUE THREAD

**Issue by j-james** [andrew-t/mines#4] opened 2020-08-17 04:38 UTC
```
Uncaught Error: Infinite loop suspected while learning
    at LogicGrid.updateKnowledge (logic-grid.js:368)
    at LogicGrid.updateKnowledge (logic-grid.js:425)
    at LogicGrid.reveal (logic-grid.js:116)
    at HTMLElement.reveal (grid.js:111)
    at HTMLElement.<anonymous> (grid.js:61)
```
![Capture](https://user-images.githubusercontent.com/35242550/90357718-c94f5080-e008-11ea-923a-94c65fdb9dcf.PNG)

Fun game :<)

**Comment by j-james** [comment] 2020-08-17 04:39
The purple-dot marked square was unable to be clicked.

**Comment by andrew-t** [comment] 2020-08-17 07:46
Hm. I assume it knew the square you clicked on was safe, so I guess it must have picked a number for the square to be and then got stuck trying to work out the implications of that number. It should be reproducable in a test if I get some time — something like `for (let m = 1; m < 5; ++m) { setSquareTo(m); updateKnowledge(); };` and might even be informative for fixing a wider bug.

**Comment by andrew-t** [comment] 2020-08-17 12:25
Update: I've reproduced this in a test and it fails only when the cell is assigned to be a 3. Not sure why yet but that's something.

**Comment by andrew-t** [comment] 2020-08-17 13:48
OK, it seems like this case was just _too_ successful and it made such a long chain of inferences that my infinite loop detection code kicked in.

I am starting to suspect I should disable some of that code but for now I have quintupled the length of chain it will accept and replaced this exception with a warning and return, since it ought to be safe to continue from any point during the 'logic' phase. With any luck that should fix this issue but feel free to re-open if it crashes again and seems like the same thing. 🙂

**Closed by andrew-t** 2020-08-17 13:48 UTC
