### ISSUE TITLE
Possible incorrect behavior based on the project description

### ISSUE THREAD

**Issue by mindviews** [andrew-t/mines#3] opened 2020-08-17 03:03 UTC
Love this concept - great fun!

Below is what I believe to be an incorrect "making a mine" because of a user click.  Here is the ending image: 
![image](https://user-images.githubusercontent.com/16233474/90352679-09ff9780-e012-11ea-9523-84346e1b97cc.png)

And here is the text output from my game session:
```
Made a mine because the user clicked it when (after an exhaustive search) there was a safe space at 0, 7: 
012*1001111*2-?
01*33322*112??-
0112***21112??2
11112321001*33*
1*21100000223*2
123*2111111*321
12*44*11*112*10
??4**2222113331
??*4322*101**3*
??*21*21101223*
 + 3 mines left to find became 
012*1001111*2--
01*33322*112-*-
0112***21112--2
11112321001*33*
1*21100000223*2
123*2111111*321
12*44*11*112*10
*-4**2222113331
-**4322*101**3*
--*21*21101223*
 + 0 mines left to find
```
If I am reading the coordinates correctly, 0,7 refers to column 0, row 7 (both zero-indexed).  The action I took to trigger this state was to right click to place a flag at 1,7, then I moved my mouse over the "4" at 2,7 and right+left clicked to trigger a clearing of the surrounding spaces (of which only one square 1,8 should have been cleared).  This triggered the end of game, I believe incorrectly.

There were 3 mines left to find at the time of the last click.  The "2" at 14,2 required one of the adjoining spaces labeled "X1" in blue to be one of the mines.  The "2" at 11, 1 (and also the "2" at 11,2) required another of the mines to be in one of the adjoining spaces labeled "X2" in red.  (There are other constraints around these squares narrowing the possibilities, but these two are non-overlapping and sufficient for determining that two mines are required leaving only one free to place elsewhere.)  This leaves only one mine remaining available on the board, so it is constrained to be at 1,7 given the available information.  The proposed solution output by the program fails to satisfy the "X2" constraint.

![image](https://user-images.githubusercontent.com/16233474/90352560-c147de80-e011-11ea-8f57-d19a0cb04d27.png)

**Comment by andrew-t** [comment] 2020-08-17 07:53
Yeah, that does seem wrong. This ought to be reproducible in a test, which is nice.

Did the game not give you an exposion and some skulls as an explanation of where the mines "really" were? If not that might be a separate issue, or possibly a result of this one.

The game can't explicitly do the X1/X2 logic you did, but it can do an exhaustive search over this many cells and should have found a valid solution. The solution in the text output is intetnonally wrong though — that's the game assuming that the space to the left of the one you flagged was a mine and deducing that that didn't make sense (which is correct per your logic). Its error is not realising the one you revealed by pressing the completed 4 is also safe for the same reason.

I thought there was an explicit check for that — before it makes a square a mine in this way it is supposed to check the square you clicked and only make it a mine if it can find a valid solution where it is one.

Now I come to think of it I assume the reason you didn't get an explosion is because having declared this cell a mine the game got into an infinite loop trying to work out where the mines could possibly go and didn't get to the "render the solution" code.

Thanks for this, it should be a good case to fix the game up on.

**Comment by andrew-t** [comment] 2020-08-17 11:48
So it seems like the explicit check was only in the case where another cell was marked as safe — not when we had to go hunting for a safe cell.

Somewhat ridiculously it actually did this search as there are some provably-safe cells in the top right region, but didn't penalise you for missing them because it correctly realised you definitely hadn't clicked on a mine. Then it did the exhaustive check which lacks that logic and gave you a mine.

Now the check logic _starts_ by exhaustively checking if a cell can possibly be safe/a mine and if either check fails then we know what the cell is. Only if we can't prove what the cell is do we advance to trying to work out if your gamble was necessary. That should solve this issue and probably a few others. I'm going to close this but obviously re-open it if the same bug comes back (although I've no idea how you'd know given how random the game is).

**Closed by andrew-t** 2020-08-17 11:48 UTC
